# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

stages:
- stage: build
  jobs:
    - job: first
      steps:
      - task: PythonScript@0
        inputs:
          scriptSource: 'inline'
          script: 'print("In first stage, job one")'
    - job: second
      steps:
      - task: PythonScript@0
        inputs:
          scriptSource: 'inline'
          script: 'print("In first stage, job two")'
    - job: third
      steps:
      - task: PythonScript@0
        inputs:
          scriptSource: 'inline'
          script: 'print("In first stage, job three")'
- stage: test
  jobs:
    - job: first
      steps:
      - task: PythonScript@0
        inputs:
          scriptSource: 'inline'
          script: 'print("In second stage, job one")'
    - job: second
      steps:
      - task: PythonScript@0
        inputs:
          scriptSource: 'inline'
          script: 'print("In second stage, job two")'
    - job: third
      steps:
      - task: PythonScript@0
        inputs:
          scriptSource: 'inline'
          script: 'print("In second stage, job three")'
- stage: finish
  jobs:
    - job: first
      steps:
      - task: PythonScript@0
        inputs:
          scriptSource: 'inline'
          script: 'print("In third stage, job one")'
    - job: second
      steps:
      - task: PythonScript@0
        inputs:
          scriptSource: 'inline'
          script: 'print("In third stage, job two")'
    - job: third
      steps:
      - task: PythonScript@0
        inputs:
          scriptSource: 'inline'
          script: 'print("In third stage, job three")'

